kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: simple-httpd
  generation: 2
  namespace: poc-intermedia
  labels:
    app: simple-httpd
    app.kubernetes.io/component: simple-httpd
    app.kubernetes.io/instance: simple-httpd
    app.kubernetes.io/part-of: poc-cicd
spec:
  lookupPolicy:
    local: false
  tags:
    - name: a9cea7709a69675d7f87a4f26010cf85e8f500d5
      from:
        kind: DockerImage
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Local
